<?php

return array(

	/*
	|--------------------------------------------------------------------------
	| Additional Compiled Classes
	|--------------------------------------------------------------------------
	|
	| Here you may specify additional classes to include in the compiled file
	| generated by the `artisan optimize` command. These should be classes
	| that are included on basically every request into the application.
	|
	*/

	'vendor/laravel/framework/src/Illuminate/Support/Collection.php',
	'vendor/laravel/framework/src/Illuminate/Database/Eloquent/Collection.php',

	'vendor/prologue/alerts/src/Prologue/Alerts/AlertsServiceProvider.php',
	'vendor/anlutro/curl/src/anlutro/cURL/Laravel/cURLServiceProvider.php',

	'vendor/andheiberg/asset/src/Andheiberg/Asset/AssetServiceProvider.php',
	'vendor/andheiberg/asset/src/Andheiberg/Asset/Facades/Asset.php',
	'vendor/andheiberg/asset/src/Andheiberg/Asset/Asset.php',
	'vendor/andheiberg/asset/src/Andheiberg/Asset/AssetManager.php',

	'vendor/andheiberg/auth/src/Andheiberg/Auth/Facades/Auth.php',
	'vendor/andheiberg/auth/src/Andheiberg/Auth/AuthServiceProvider.php',
	'vendor/andheiberg/auth/src/Andheiberg/Auth/AuthManager.php',
	'vendor/andheiberg/auth/src/Andheiberg/Auth/EloquentUserProvider.php',
	'vendor/andheiberg/auth/src/Andheiberg/Auth/UserProviderInterface.php',
	'vendor/andheiberg/auth/src/Andheiberg/Auth/Guard.php',
	'vendor/andheiberg/auth/src/Andheiberg/Auth/Reminders/ReminderServiceProvider.php',
	'vendor/andheiberg/auth/src/Andheiberg/Auth/Reminders/DatabaseReminderRepository.php',
	'vendor/andheiberg/auth/src/Andheiberg/Auth/Reminders/ReminderRepositoryInterface.php',
	'vendor/andheiberg/auth/src/Andheiberg/Auth/Reminders/EmailVerificationBroker.php',
	'vendor/andheiberg/auth/src/Andheiberg/Auth/Reminders/RemindableInterface.php',
	'vendor/laravel/framework/src/Illuminate/Validation/ValidationServiceProvider.php',
	'vendor/andheiberg/auth/src/Andheiberg/Auth/UserInterface.php',
	'vendor/andheiberg/auth/src/Andheiberg/Auth/Models/User.php',
	'app/models/User.php',
);